### ISSUE TITLE
Astropy Model class error?

### ISSUE THREAD

**Issue by iancrossfield** [lisadang27/SPCA#13]
When trying to intialize the SPCA code via 
>> from SPCA import frameDiagnosticsBackend
I get the error:
>>TypeError: object of type '_ModelMeta' has no len()
at line 2357 in astropy/modeling/core.py:
-> 2357         if op != 'fix_inputs' and len(left) != len(right):

(I have astropy v4.0). The error above seems to be the same issue described in this Astropy Pull request here:
https://github.com/astropy/astropy/pull/8769
It may also describe (or at least hint at) a workaround.

**Comment by taylorbell57** [comment]
Hi Ian, thanks for trying out SPCA and for letting us know about this issue for you! I too am running astropy v4.0, so that can't be the source of the issue. Given some reading of that thread you linked to and the fact that you encounter this issue when importing frameDiagnosticsBackend, I think the issue can't be in our code as the only thing that happens is some other packages get imported. Instead, you must be using an older version of one of the packages we import.

If there is more content in the error message you get, it'd be useful to see the full back trace to know which package the issue is coming from. My best guess is that we are using different versions of photutils - I am using 0.7.2. If this ends up being an issue, I'll make sure to specify this requirement.

You can upgrade your photutils package using `pip install --upgrade photutils` or `conda upgrade photutils`.

**Comment by taylorbell57** [comment]
I have just confirmed locally that `photutils<0.7` will give the error message you received, while `photutils>=0.7` will not. I'll make sure to include this in the setup.py file! Let me know if the issue still persists for you @iancrossfield, otherwise I'll close this issue

**Comment by iancrossfield** [comment]
Thanks @taylorbell57 - agreed that this was caused by a broken (and <0.7) photutils installation. The line "from SPCA import frameDiagnosticsBackend" now executes without errors. Closing this issue.
