### ISSUE TITLE
Planet-lookup fails for planets not yet in exoplanet archive database

### ISSUE THREAD

**Issue by iancrossfield** [lisadang27/SPCA#15]
The  Poly-BLISS-GP file looks up a planet and its parameters in a curated CSV file (downloaded automatically). However, this fails in the edge case of a planet observed by Spitzer but not yet in the exoplanet archive!  (E.g., new TESS planets that were rapidly observed with Spitzer).

For now, I'll just hack some workarounds and work the relevant parameters in manually. And in a year or two this hopefully won't be an issue for any phase-curve systems.

**Comment by taylorbell57** [comment]
Hi Ian,

Another beta-tester also encountered this for a TOI object. I've already implemented a fix in the branch addingPLD which I will be merging into the master branch within a week. This merge will come with a bunch of other upgrades (including an implementation of PLD and moving much of the code that you see within the decorrelation notebook to a separate python file so that you don't see code that you don't need to tweak). For now, you could look at that branch for an idea of what you need to manually put into the p0_obj parameter. Once I've merged this into master, I'll close this issue.

**Comment by taylorbell57** [comment]
The option to custom load a planet's data is now implemented and tested as of commit bbe35a9 (v0.2)
